### ISSUE TITLE
Faviconがけいおん！風のやつから変わらない...

### ISSUE THREAD

**Issue by totzyuta** [okadai-techlab/okayama-u-techlab.com#11]

**Comment by dai199** [comment]
どの画像に変更したいの？？

**Comment by totzyuta** [comment]
OTLのロゴにしたいなと思ってます。

**Comment by dai199** [comment]
ロゴ画像もらえれば対応します！！
ロゴ画像もレポジトリに入れておいてくれない？？

**Comment by totzyuta** [comment]
多分サーバーの方の問題かと思います...。権限なども確認したのですが。もう一度確認してあげてみます。ロゴは`/public/img/favicon.png`のものを使おうと思ってます

https://github.com/okadai-techlab/okayama-u-techlab.com/blob/master/public/img/favicon.png

**Comment by dai199** [comment]
個人的にshotcutがないのが気持ち悪いなぁって思ったんやけど、関係ないか
http://www.dspt.net/html_tag/001_data/027.html

**Comment by totzyuta** [comment]
変わらない...ググったのですが分かりませんでした... :sob:

**Comment by dai199** [comment]
ふぅむ。
icoとpng両方書けば？？

**Comment by totzyuta** [comment]
やってみます...！

**Comment by totzyuta** [comment]
なんか変わってましたー笑

closeします！

**Comment by dai199** [comment]
ほほうｗよかったｗ
