### ISSUE TITLE
スマフォページのデザイン修正

### ISSUE THREAD

**Issue by totzyuta** [okadai-techlab/okayama-u-techlab.com#2]
- Members
- Products

**Comment by dai199** [comment]
・メンバーはそれぞれにgithubの練習として追加してもらう
・プロダクトのとこは #8 と関連するのでそこで修正したほうがいいかも

メンバーページは別ページに作って、代表副代表だけトップにのせるとかでもOK

**Comment by totzyuta** [comment]
:+1:
