### ISSUE TITLE
Contact form for Slack Notification

### ISSUE THREAD

**Issue by totzyuta** [okadai-techlab/okayama-u-techlab.com#25]
今お問い合わせフォームあるのだけど、多分gmailの2段階認証外したから動いてない気がする...笑

考えてみればこれでメール飛ばす必要なくて、Slackに流しちゃえばそれでいいかなと思いました :massage:

**Comment by dai199** [comment]
マジ？8月くらいのときは届いてたけど・・・

**Comment by totzyuta** [comment]
あれ、今なってましたかね！じゃあメールの方はそのままで大丈夫ですね(_ﾟ▽ﾟ_)

追加でSlackへも流すのはどう思いますか？ :heart_eyes_cat: 
みんなが知れたらいいのかなーと思いました :bulb:

**Comment by dai199** [comment]
確かにそれはいいかもー！
ぐぐって、これいいじゃん！って思ったら凸だったｗ
http://totutotu.hatenablog.com/entry/2015/08/28/Rails%E3%82%A2%E3%83%97%E3%83%AA%E3%81%8B%E3%82%89Slack%E3%81%B8%E9%80%9A%E7%9F%A5%E3%81%99%E3%82%8B

**Comment by totzyuta** [comment]
それは笑

**Comment by dai199** [comment]
あ、これ追加で消すの忘れてたので消しますー
