### ISSUE TITLE
ContactFormが死んでる

### ISSUE THREAD

**Issue by dai199** [okadai-techlab/okayama-u-techlab.com#32]
ContactFormが死んでる・・・(´・ω・｀)うまくGmailと接続出来ないお
むしろメールじゃなくてSlackに通知したいけど、どんな内容が来たかどうかは保存しておきたいから結局メールのほうに送っておいたほうが便利

早めになおしたいけど、Gmailアカウント公開してるから別にいいかなぁっていうのはある。

**Comment by totzyuta** [comment]
ymlファイルでメールアドレスなど設定しているので、`config/settings.yml`を追加する必要がありました！！

**Comment by dai199** [comment]
ymlは既に追加して、
`Net::SMTPAuthenticationError - 534-5.7.14 <https://accounts.google.com/ContinueSignIn?****`
みたいなエラーがlogに吐き出されてたんだけど、ぐぐってたら[このGoogle公式ページ](https://support.google.com/accounts/answer/6009563)にいけて、そこにある
`https://accounts.google.com/b/0/DisplayUnlockCaptcha`ってURLにアクセスして、`***/b/0/***`のところをてくらぼGmailでアクセスしている番号に変えて許可したらいけるようになった！ようわからんけどようわかった！ｗ
