### ISSUE TITLE
スマホでつくったものリストの「ALL」とか触ろうとするとtouch出来ない

### ISSUE THREAD

**Issue by dai199** [okadai-techlab/okayama-u-techlab.com#8]
ウワサ―とかコーヒーノートのdivが「ALL」とか「WEB」のとこに覆いかぶさってるのが原因

**Comment by totzyuta** [comment]
説明のやつ書いたらスンゲーはみ出てしまい。。。笑

**Comment by dai199** [comment]
説明文字制限作る？今色々やろうとしてるけどそもそも文字数多いからどうしようもないｗ

**Comment by totzyuta** [comment]
そうなんですよね。。。そうしますか。

それかちょっと面倒ですがそもそもあれスマフォの表示に向いてないと思うので表示の仕方を変えて最初から説明が表示されてた方がいい気がするのですよね。一回タップで説明表示、二回目でリンクへ飛ぶってのがUX力ない。。。笑

**Comment by dai199** [comment]
面倒だねーｗ 
下に説明書いたりする？

**Comment by totzyuta** [comment]
それがいいかもしれないですね笑

**Comment by dai199** [comment]
これ結構前になおってたからclose！
